#kubectl run nginx --image=nginx --restart=Never --requests=memory=100,cpu=10m --dry-run -oyaml                              Mon Feb 24 09:23:00 2020
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 10m
        memory: "100"

#kubectl run nginx --image=nginx --restart=Never --requests=memory=100,cpu=10m --limits=memory=500Mi,cpu=100m --dry-run -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: "100"
